const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({ headless: false });
    const page = await browser.newPage();

    // Step 1: Open GroupMe login page
    await page.goto("https://web.groupme.com/");
    console.log("Log in manually, open a chat, and then press Enter in the terminal to start...");
    await new Promise(resolve => process.stdin.once("data", resolve)); // Wait for Enter key press

    try {
        // Step 2: Wait for the message input field to be available
        const inputSelector = 'div[contenteditable="true"]';
        await page.waitForSelector(inputSelector, { visible: true, timeout: 10000 });

        console.log("✅ Chat detected. Monitoring for new messages...");

        let lastMessage = ""; // Store last detected message
        let lastResponse = ""; // Store last sent response

        // **Your Profile Image URL to Identify Your Messages**
        const userImageUrl = "https://i.groupme.com/498x498.gif.ab8e43ed40304fddb181d08534f39d47.avatar";

        // **Responses List (Formatted for Easy Editing)**
        const responses = [
            "yoo",
            "aint no way",
            "fr lol",
            "damn",
            "hahahaha",
            "alright bro",
            "nahhhh",
            "okay",
            "interesting..",
            "food?",
            "LOL",
            "my dream life fr",
            "ur a bot",
            "no way",
            "are we being fr rn",
            "bro what",
            "lmaooo",
            "nah that’s crazy",
            "I can’t rn",
            "bro wtf",
            "that’s wild",
            "say less",
            "nah u tweaking",
            "bro trust",
            "u deadass?",
            "yo chill",
            "I’m crying",
            "not even surprised",
            "bro stop",
            "he cooked",
            "real talk",
            "this some movie type beat",
            "no shot",
            "thats OD",
            "bet bro",
            "bruhhh",
            "not like this",
            "bro im weak",
            "nah bro",
            "let him cook",
            "lowkey tho",
            "you cappin",
            "bro…",
            "say that then",
            "big W",
            "ratio",
            "wild take",
            "it’s giving...",
            "I felt that",
            "this can’t be real",
            "yo wtf",
            "stop playin",
            "outta pocket",
            "on god?",
            "bro cooked",
            "nah thats foul",
            "not even gonna lie",
            "bro be serious",
            "this a fever dream",
            "ion believe it",
            "this crazy",
            "you wildin",
            "I need context",
            "no way you said that",
            "ayooo?",
            "I knew it",
            "say swear",
            "bro really said that",
            "delete this",
            "why u like this",
            "pack it up",
            "you gotta be kidding",
            "bro be fr",
            "u lying",
            "this a joke?",
            "im done",
            "aint no way thats real",
            "bro whats the play",
            "chill out",
            "nah this wild",
            "who asked",
            "ratio+bozo",
            "outta pocket fr",
            "why you say that",
            "oh nahhh",
            "thats a setup",
            "bro fell off",
            "nah bro cooked",
            "bro got a point",
            "who approved this",
            "somebody stop him",
            "what in the world",
            "is this real life",
            "nah you got it",
            "bro you good?",
            "please explain",
            "bruh moment",
            "bro lost it",
            "we all thinking it",
            "Im speechless",
            "thats beyond me",
            "say that louder",
            "this too much",
            "you trippin",
            "bro u tweaking",
            "thats a reach",
            "nah lets not do this",
            "I aint ready for this",
            "bro you tryna be funny?",
            "this is comedy",
            "now you just saying anything",
            "explain yourself",
            "nah I need receipts",
            "bold move",
            "bro move different",
            "why you like this fr",
            "I was not ready for this",
            "the streets need answers",
            "ok but why tho?",
            "thats wild behavior",
            "this energy is unmatched",
            "delete that immediately",
            "bro in his villain arc",
            "you too deep in the lore",
            "nah u playing too much",
            "what kinda timeline is this",
            "bro out here on expert mode",
            "this the content I needed",
            "whats even the context here ??",
            "somebody come get their mans",
            "this aint even real life",
            "nah u lost me",
            "that’s a war crime",
            "Im questioning everything",
            "my brain can’t process this",
            "bro move in silence like lasagna",
            "you might be onto something",
            "bro this is chaos",
            "we need a meeting",
            "nah bro gotta be stopped",
            "somebody check on him",
            "bro dropped lore",
            "you a whole NPC",
            "this a no from me",
            "nah this a fever dream",
            "bro woke up and chose violence",
            "this is top-tier nonsense",
            "why would you say this",
            "hold up… what lmfao?",
            "nah we not letting this slide",
            "you win this round",
            "bro needs a timeout",
            "that was unnecessary",
            "you got 5 seconds to explain",
            "who gave you internet access",
            "bro tweaking for real",
            "not you saying this rn",
            "I cant even be mad",
            "this is villain behavior",
            "we need to unpack this",
            "bro this is poetry",
            "some things should stay unsaid",
            "why you exposing yourself like this",
            "this gonna haunt me",
            "nah run that back",
            "this info was not needed",
            "bro you outta pocket",
            "that was unprovoked",
            "we got a live one",
            "Im ignoring this",
            "bro took it personally",
            "u gotta chill",
            "this cant be a real take",
            "why do you know this",
            "stop talking immediately",
            "bro just typed and hit send",
            "you woke up and chose this?",
            "this gotta be satire",
            "nah we gotta fight",
            "bro talking like a final boss",
            "somebody revoke your wifi",
            "why are we like this",
            "this aint normal behavior",
            "explain in 3 words or less",
            "bro cooking something",
            "nah this cryptic",
            "you sure about that?",
            "who hurt you",
            "sis in shambles",
            "say it louder",
            "this a skill issue",
            "left us speechless",
            "nah this man different",
            "this response is concerning",
            "somebody tell him to stop",
            "you just be talking huh",
            "this better be a joke",
            "not what I expected",
            "bro typed this with confidence",
            "this actually concerning",
            "I got no words",
            "bro got unlimited audacity",
            "nah this sinister",
            "stop before its too late",
            "plz stop going off the rails bo",
            "I want no part in this",
            "this some top-tier trolling",
            "bro got some explaining to do",
            "this gotta be illegal somewhere",
            "somebody check on this man",
            "bro on another wavelength",
            "this is generational chaos",
            "why you saying this out loud",
            "this energy is too strong",
            "bro taking risks",
            "you on thin ice",
            "this take is outlandish",
            "u just casually dropped this?",
            "I refuse to process this",
            "bro in ultra instinct mode",
            "this a real problem",
            "I might log off",
            "bruh you ok?",
            "I need a break",
            "somebody call backup",
            "bro going through something",
            "this has consequences",
            "this might be illegal",
            "bro a different breed",
            "Im gonna pretend I ain’t see that shi",
            "this another level of chaos",
            "this an emergency",
            "why are you like this",
            "you running outta chances",
            "bro u just broke the game lmfao",
            "this gotta be a speedrun",
            "u gonna regret this",
            "I need an explanation",
            "this needs to be studied",
            "nah this some dark magic",
            "bro on a mission",
            "I wasnt prepared for this",
            "this the plot twist",
            "stop playing life on expert mode",
            "we need damage control",
            "nah bro needs a cooldown",
            "u got no filter",
            "this a level 10 threat",
            "bro hit the chaos button",
            "this man different",
            "you operating on another frequency",
            "this is reckless",
            "just threw logic out the window",
            "Im reporting ts",
            "u got no chill",
            "this an attack on my sanity",
            "Im concerned for you",
            "bro in another dimension",
            "this gonna be studied in history",
            "bro might needs a reality check fr",
            "nah this diabolical",
            "sis got 0 self-control",
            "this is beyond me",
            "bro chose a dangerous path",
            "this a national emergency",
            "u just changed the timeline",
            "we need a strategy",
            "this man playing 4D chess",
            "bro just set the internet on fire",
            "this man too powerful",
            "stop u a menace fr",
            "this should be classified info",
            "bro pulling out ancient knowledge",
            "we need a firewall for you",
            "girl turned into a philosopher",
            "nah you moving reckless",
            "this a different timeline fr",
            "bro just sent us into the multiverse",
            "this a danger to society",
            "bro rewriting history",
            "we need a containment unit",
            "bro needs to be nerfed",
            "this might start a war",
            "girl dropping prophecy",
            "we need immediate intervention",
            "bro hacking reality",
            "this a cursed timeline",
            "bro tapped into forbidden knowledge",
            "nah you playing too dangerous",
            "this beyond comprehension",
            "bro making up lore now",
            "this has government implications",
            "we need to intervene",
            "bro unlocked a hidden level",
            "this gotta be a prank",
            "dropping facts unprovoked",
            "this is historic",
            "bro rewriting the code of life",
            "somebody gotta nerf this man",
            "opened Pandora’s box fr lol",
            "this man went too far",
            "that summoning demons fr",
            "we need a cease and desist",
            "we spitting universal truths now?",
            "this a top 10 moment",
            "bro bending reality",
            "nah this legendary",
            "bro unlocked god mode",
            "this information dangerous",
            "u exposing the matrix fr",
            "nah you just freestyling now",
            "this a ripple in time",
            "stop hacking the simulation",
            "we need an investigation",
            "this a forbidden message",
            "bro decoding ancient texts",
            "this is an omen",
            "bout to start a revolution",
            "we all in danger now",
            "BROTHER?",
            "bro too powerful for this world",
            "Nah",
            "yuuuup",
            "bet",
            "Cap",
            "fax",
            "Damn",
            "sheesh",
            "wild honestly",
            "wym?",
            "chill",
            "Bruh",
            "Ayo?",
            "word",
            "deadass?",
            "true",
            "lame",
            "Ehh",
            "welp",
            "sus",
            "thats a vibe",
            "simp",
            "yikes",
            "gone",
            "rip",
            "Frr",
            "lowkey",
            "Mid",
            "Lit",
            "valid",
            "Crazy",
            "cooked",
            "Lost",
            "Sideeye",
            "Done",
            "Lost it",
            "lied",
            "forreal?",
            "Oof",
            "bruhh",
            "say less",
            "lurking",
            "Whew",
            "chillax",
            "ghosted",
            "mild style",
            "Who?",
            "Where?",
            "how?",
            "guess",
            "try again",
            "No shot",
            "Def",
            "Nahhh",
            "Aight",
            "For sure bro",
            "yeet",
            "Skrrt",
            "rollin",
            "pfft",
            "Hmph",
            "whew",
            "bruhh",
            "sick",
            "huh",
            "Meh",
            "ngl",
            "valid",
            "ts peak",
            "pain",
            "Zzz",
            "basic",
            "jokes",
            "L+Ratio",
            "naaaaah fr hahahaha",
            "loud",
            "weak",
            "hot take",
            "tough",
            "kinda",
            "dead",
            "extra",
            "Dry",
            "who tryna go out",
            "wtm",
            "wasted",
            "jucked out",
            "janky",
            "nice fumble",
            "sketchy asf",
            "hard pass",
            "dumb",
            "lurked",
            "late",
            "eh?",
            "risky af",
            "goofy",
            "baited",
            "Cool",
            "K",
            "Ok",
            "bet",
            "Eh",
            "nice",
            "wild",
            "Aight.",
            "Ight.",
            "sure",
            "Idc",
            "Idk",
            "nope",
            "yep",
            "yup",
            "Oh",
            "Mhmm.",
            "Alright",
            "Wait",
            "Huh",
            "Wow",
            "oof",
            "crazy",
            "Seen",
            "noted",
            "Dunno",
            "Oh fr?",
            "Why?",
            "What?",
            "How?",
            "Lmao.",
            "Ok cool.",
            "Meh.",
            "Mmm.",
            "Ehh",
            "Oh ok.",
            "Kk.",
            "Oh wow.",
            "yea.",
            "ya",
            "hmm",
            "bruh",
            "sheesh",
            "sure ig",
            "guess so",
            "makes sense",
            "word",
            "true",
            "damn.",
            "i see",
            "ayo.",
            "wild tbh.",
            "could be",
            "might be.",
            "nvm.",
            "no way.",
            "Fr?",
            "Say that",
            "not rly.",
            "couldnt be me",
            "mid",
            "lowkey",
            "highkey",
            "seen it",
            "classic",
            "rare W",
            "rare L",
            "Yikes",
            "Oop",
            "Tough",
            "big L.",
            "big W.",
            "lost me.",
            "not even",
            "knew it",
            "Wait fr?",
            "If u say so",
            "Do u",
            "I guess",
            "Hard to say",
            "idk bro",
            "dont care",
            "a lil bit",
            "could be worse",
            "aight bet",
            "try again",
            "not sure",
            "thats wild",
            "yea no",
            "wait what?",
            "wouldnt be me",
            "bet that",
            "sounds fake",
            "idk man",
            "cool story",
            "big if true",
            "real",
            "none your business bro",
            "i be talking way too much on this app",
            "ts pmo",
            "ts so frutiger aero",
            "avian needa chill rn bruhh",
            "im not gonna answer any questions bro",
            "don feel like conversing rn",
            "i just be saying random things honestly",
            "why do u even care bro",
            "rent free",
            "im just bored lol",
            "idk im just bed rotting",
            "lemme chat in peace",
            "am i not allowed to talk?",
            "just having a conversation bro",
            "i should probably get to sleep no lie",
            "im so tired but i dont wanna go to bed lol",
            "real",
            "sure",
            "sure :p",
            "doesnt concern u honestly",
            "u may wanna look in the mirror",
            "groupme sucks ahh",
            "this app sucks ahh",
            "theresa sucks ahh",
            "bonnie needs to chill",
            "i think its time u guys go to bed",
            "lowkey its bedtime yall plz log off",
            "you don even know me bro",
            "im so sleepy what the heck",
            "should i take a break from this app or nah guys",
            "u could say im an... introvert",
            "i can feel my eyes getting heavy im boutta crash",
            "u goofy af lol",
            "time to take a shower",
            "chill lol",
            "its not that serious",
            "im so done",
            "im boutta drop the H bomb... heck you",
            "why u so cross rn",
            "jobs bro... jobs..",
            "you should probably see a therapist about that",
            "whats it matter to u honestly",
            "nah ima do my own thing",
            "do u really think i care rn",
            "just live ur life bro",
            "im so glad im unemployed",
            "yeah :p",
            "i needa sit down fr",
            "should i take a break from this app or nah",
            "god im so tired",
            "not complaining",
            "im not even doing anything lol",
            "im just sitting down",
            "im just laying down now",
            "boutta fall asleep into my pillow fr",
            "ts so annoying",
            "say it louder",
            "who playin games",
            "thats actually straight facts ngl",
            "take a chill pill bro",
            "fries. bag. now.",
            "time to put the fries in the bag",
            "dont yall have homework to do lmao",
            "you cannot be real",
            "there is no way your real",
            "i refuse to believe your real",
            "grammar",
            "easy for you to say",
            "like i said thats easy for u to say lol",
            "u ok?",
            "i need to take a break from this app lowkey",
            "im online 24/7 at this point",
            "do u even go to ksu",
            "it doesnt matter bro",
            "dude chill",
            "im just vibing",
            "dont get pressed",
            "you wont believe what im boutta tell u",
            "time for sleepy time",
            "anyone eating noodles rn",
            "im hungry anyone got food",
            "im boutta crash out",
            "dont crash out on me",
            "come on bro it cant be that bad",
            "what are u even saying rn",
            "im chilling",
            "anyone know the tallest bridge in kennesaw asking for a friend",
            "dookie dorms",
            "speedrunning life rn",
            "speedrunning my social life rn",
            "the bills cannot be this high",
            "just let it out bro",
            "are u on any medication by chance",
            "do u take antidepressants by chance",
            "ur still my brother from another mother",
            "why u say ts",
            "im always online lowkey bruh",
            "roblox did not deserve to come into 2025 bro",
            "ima say it honestly, marvel rivals sucks ahhhhh",
            "i just be saying random things bro",
            "hahahahahaha",
            "thats actually funny lmao",
            "was that supposed to be funny",
            "im not laughing",
            "gyatt",
            "grown ahh man btw",
            "are u even real",
            "grown ahh woman btw",
            "ts not real",
            "im so pressed rn",
            "someone send me some money",
            "someone send me cash rn",
            "send me food rn plz",
            "idec at this point",
            "doesnt matter lol",
            "dont make me say it",
            "u know what u might be right",
            "its time to take a break from groupme broski",
            "idc..",
            "lol",
            "lmfao",
            "alr lol",
            "ok?",
            "thats cool ig",
            "idc bro",
            "no one asked",
            "im not gonna asnwer your questions",
            "im not gonna interact with your questions",
            "try again later bro",
            "aint no way ur actually real",
            "im just jk lol",
            "im just joking mate",
            "chill lol just joking broo",
            "are u ready to have a serious conversation",
            "as long as u dont gaslight",
            "the binary code that creates",
            "cyber core > dream core",
            "i spend way too much time on this app.....",
            "anyone wanna be my friend or nah",
            "anyone else watching anime rn",
            "im streaming on twitch rn",
            "magic 8 ball ahh answers",
            "im honestly cant read",
            "u really think i have the mental capacity to read that",
            "IM JK ;p",
            "it was never that serious in the first place to be fair",
            "to be fair ur prolly right",
            "for once ur speaking facts",
            "thats actually straight facts holy",
            "thats just your opinion man",
            "ok",
            "sure yeah",
            "i see it now",
            "i totally understand bro",
            "nah u right u right",
            "damn..",
            "okay satan",
            "i needa get off my computer fr",
            "ts making me tired",
            "im go bed",
            "whatver"



            
            
        ];

        // **Shuffle array function (Fisher-Yates shuffle)**
        function shuffleArray(array) {
            for (let i = array.length - 1; i > 0; i--) {
                const j = Math.floor(Math.random() * (i + 1));
                [array[i], array[j]] = [array[j], array[i]];
            }
        }

        // **Response tracking list**
        let responseQueue = [...responses]; // Clone the responses array
        shuffleArray(responseQueue); // Shuffle at the start

        // **Function to get a response that isn't repeated until all have been used**
        function getRandomResponse() {
            if (responseQueue.length === 0) {
                // All responses have been used, reset and shuffle again
                responseQueue = [...responses];
                shuffleArray(responseQueue);
            }

            lastResponse = responseQueue.shift(); // Take the first item from the queue
            return lastResponse;
        }

        // **Function to get the latest message in chat**
        async function getLatestMessage() {
            const messageElements = await page.$$('.chat-messages .message'); // Get all message elements
            if (messageElements.length > 0) {
                const lastMessageElement = messageElements[messageElements.length - 1];
                const messageText = await page.evaluate(el => el.innerText.trim(), lastMessageElement);

                // Get the author's profile image
                const authorImageElement = await lastMessageElement.$('.avatar img');
                let authorImageUrl = "";
                if (authorImageElement) {
                    authorImageUrl = await page.evaluate(img => img.src, authorImageElement);
                }

                return { text: messageText, authorImageUrl };
            }
            return null;
        }

        // Step 3: Record the initial message at startup (so it doesn’t send immediately)
        const initialMessage = await getLatestMessage();
        if (initialMessage) {
            lastMessage = initialMessage.text;
            console.log(`✅ Initial message recorded: "${lastMessage}"`);
        }

        // Step 4: Monitor for new messages
        while (true) {
            let newMessage;

            // **Wait until a new message appears**
            do {
                await new Promise(resolve => setTimeout(resolve, 90000)); // Check every 160 seconds
                newMessage = await getLatestMessage();
            } while (!newMessage || newMessage.text === lastMessage);

            // **If the message is from yourself, ignore it**
            if (newMessage.authorImageUrl === userImageUrl) {
                console.log(`🔄 Your own message detected: "${newMessage.text}". Ignoring...`);
                lastMessage = newMessage.text; // Update lastMessage but don't respond
                continue;
            }

            // **If the last detected message is the same as the last response, ignore it**
            if (newMessage.text === lastResponse) {
                console.log(`🔄 Last detected message is my own response: "${newMessage.text}". Ignoring...`);
                lastMessage = newMessage.text;
                continue;
            }

            // **New message detected**
            console.log(`🆕 New message detected: "${newMessage.text}"`);
            lastMessage = newMessage.text; // Update last message

            // **Select a random response**
            const randomResponse = getRandomResponse();

            // Step 5: Send the random response
            const inputBox = await page.$(inputSelector);
            if (inputBox) {
                await inputBox.click(); // Focus on the input box
                await page.type(inputSelector, randomResponse, { delay: 100 }); // Type the response
                await page.keyboard.press("Enter"); // Send the message

                console.log(`✅ Sent response: "${randomResponse}"`);
            } else {
                console.log("⚠️ Could not find input box.");
            }
        }

    } catch (err) {
        console.log("❌ Error:", err);
    }

    // Keep the browser open
})();
